// Document Object Model (DOM):
/*
When a site opens in a browser window. Browser itself creates
a global object called "window". Window object has a "document"
object inside it. This document object then has access to all
of our html code and the connected css code. So basically the
document object is a gateway to our html and css code of the
site. And now for the best part, Js has access to the window
object. Which provides it access to the document object and
all of the docements content as well, hence our Js is allowed
to not only access the html tags and their css properties, but
also manipulate them. This entire tree of nodes generated by the
browser is called DOM, which is short for Document Object Model.
*/
// We can change the background color using:
const bgColor = prompt("Enter a Color:");
const root = document.documentElement; // returns reference to :root or <html>
if (bgColor)
    root.style.setProperty("--body-color", bgColor);
// Similar methods:
const myH1_I = document.getElementById("myH1-I"); // returns a single reference
const myH1_C = document.getElementsByClassName("myH1-C"); // returns an object of references
const h1_Tag = document.getElementsByTagName("h1"); // returns an object of references
// Similarly a one for all method: (Determines natures like id, class or tag by prefixes)
const target1 = document.querySelector("#myH1-I");  // returns a single reference
const target2 = document.querySelectorAll(".myH1-C");  // returns a NodeList of references
const target3 = document.querySelectorAll("h1");  // returns a NodeList of references
// Properties:
const myH1_I_TagName = myH1_I.tagName; // returns tag name of stored reference
const myH1_I_InnerText = myH1_I.innerText; // returns inner text of stored reference
const body_html = document.body.innerHTML; // return contents as plain text
const fChild_root = root.firstChild; // returns firstChild Node of target
const lChild_root = root.lastChild; // returns lastChild Node of target
const children = document.body.children; // returns collection of child Nodes of target
